# Generated by Django 3.2.8 on 2021-10-12 13:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('cate_name', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pic_address', models.CharField(max_length=100)),
                ('goods_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('onsale_count', models.IntegerField(blank=True, null=True)),
                ('clear_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'goods',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Shopcart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.usersinfo')),
                ('goods_num', models.IntegerField(blank=True, null=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='information.goods')),
            ],
            options={
                'db_table': 'shopcart',
                'managed': True,
                'unique_together': {('user', 'goods')},
            },
        ),
        migrations.CreateModel(
            name='Orderinfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.usersinfo')),
                ('purc_count', models.IntegerField(blank=True, null=True)),
                ('order_state', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('audit_manager_id1', models.CharField(blank=True, max_length=9, null=True)),
                ('audit_manager_id2', models.CharField(blank=True, max_length=9, null=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='information.goods')),
            ],
            options={
                'db_table': 'orderinfo',
                'managed': True,
                'unique_together': {('user', 'goods')},
            },
        ),
        migrations.CreateModel(
            name='Interfacemanagement',
            fields=[
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.manager')),
                ('operatetype', models.CharField(blank=True, db_column='OperateType', max_length=1, null=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='information.goods')),
            ],
            options={
                'db_table': 'interfacemanagement',
                'managed': True,
                'unique_together': {('manager', 'goods')},
            },
        ),
        migrations.CreateModel(
            name='Customerservice',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.usersinfo')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.manager')),
            ],
            options={
                'db_table': 'customerservice',
                'managed': True,
                'unique_together': {('user', 'manager')},
            },
        ),
        migrations.CreateModel(
            name='Goodsbelong',
            fields=[
                ('goods', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='information.goods')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='information.category')),
            ],
            options={
                'db_table': 'goodsbelong',
                'managed': True,
                'unique_together': {('goods', 'cate')},
            },
        ),
    ]
