# Generated by Django 3.2.8 on 2021-10-13 04:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_id',
            field=models.CharField(max_length=1, primary_key=True, serialize=False, verbose_name='商品类别编号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.usersinfo'),
        ),
        migrations.AlterUniqueTogether(
            name='orderinfo',
            unique_together=set(),
        ),
    ]
