# Generated by Django 3.2.8 on 2021-10-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20211013_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='create_time',
        ),
    ]
